### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by hadim** [ZhuangLab/storm-analysis#15]
@HazenBabcock 

`lapack` package is available for Windows in conda forge but not `fftw` at the moment.

Beside that there is an issue compiling extensions under Windows : 

Using MSVC 2015 :

```
LINK : error LNK2001: unresolved external symbol PyInit__fista_decon_utilities
```

Using mingw64 toolchain : 

```
Cannot export PyInit__fista_decon_utilities: symbol not defined
```

Looks like the compiler is looking for a `PyInit` function but since the extension are pure C/C++ it can't find them. That is very weird because it works fine on Linux... 

I asked around but I don't know how to fix that... so for now `storm-analysis` can be compiled on Windows with the `setup.py`.

**Comment by HazenBabcock** [comment]
I'll take a look. I've installed Anaconda and followed the install instructions up to:
```
conda install fftw
```
Is there some way to get `fftw` outside of conda forge so that I can also run the windows tests?

**Comment by hadim** [comment]
Not for now, you should comment the line that compile `fftw` dependent extensions in the `setup.py`.

**Comment by HazenBabcock** [comment]
Do you know when fftw might make into Anaconda? In a few weeks? Months?

**Comment by hadim** [comment]
No idea... I asked several time about it in the PR threads on the feedstock repo and I got no answer for now. Maybe you could ask them there and see if you got an answer.

**Comment by HazenBabcock** [comment]
I have made some pretty extensive changes to how this project is built, which now makes it possible for me to build it on Windows and create wheels. I've changed all the C libraries so that they are built separately using SCons rather than as Python C extensions. The problem, as we both have found, is that Python C extensions are difficult to build on Windows. My understanding is that they require that you use the same compiler that was used to compile Python. They are also the likely source of your error, though I don't pretend to understand why a Windows Python C extension would be required to have this function, but a Linux extension would not. As the C libraries in this project are all accessed using ctypes directly callable from Python is an unnecessary constraint so it is easier to just build them separately, which is basically what I was doing before in a very hackish fashion using a bunch of .bat files. Using SCons lets us have a system that works on both Linux and Windows and that is relatively easy to run:

`python setup.py build_c`

You run this before installing and it generates all the necessary C libraries in the `storm_analysis/c_libraries` folder.

This is all in the `development` branch, and since we now have wheels for 64 bit Windows this will become `master` soon.

The root README.md describes the various installation options. Though I suspect the Anaconda instructions won't work anymore due to the above changes and will need to updated.

**Comment by hadim** [comment]
I am happy you've find a workaround about C extension. Your solution seems good.

**Comment by HazenBabcock** [comment]
I updated the Anaconda instructions. Could you take a look and maybe tell me if they work for you?

I removed both `lapack` and `fftw` from the `conda install ..` command for now because SCons was not finding these C libraries. It would probably be better to use the Anaconda libraries if they are available, but this is going to take some more work.

**Comment by hadim** [comment]
I confirm it worked for me on Linux. Good job.

**Comment by HazenBabcock** [comment]
Ok, I'm going to close this for now. Please re-open it if you run into trouble on Windows. Also, thanks again for all of your help.
